### PR TITLE
Fixed null ref exception and fixed example config in readme

### PR DESCRIPTION
**Pull request by trekco**
please update the nuget package after merge

### CODE REVIEW

**Comment by Philo** [comment]
Thanks @trekco, I'll review this next week and merge.

**Comment by Philo** [comment]
Thanks @trekco - v0.1.1 should be on nuget.

**Comment by trekco** [comment]
@Philo Thank you

**Comment by trekco** [comment]
@Philo Great lib by the way, small, easy to implement, and does what it needs to do

**Pull request merged**
